<?php

namespace Rigbag\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
	public function search( $q, $params = array() ) {
	
		extract( $params );
	
	
			$qb		= $this->createQueryBuilder('c');
				
			$query = $qb->where( $qb->expr()->like('c.name', ':q')  );
	
				
			$query->setParameter( 'q', '%' . $q . '%' );
	
				
			if( isset( $offset ) ) {
				$query->setFirstResult( $offset );
			}
			if( isset( $limit ) ) {
				$query->setMaxResults( $limit );
			}
	
			$query->addOrderBy('c.name', 'ASC');
	
	
			$result = $query->getQuery()->getResult();
	
				
			return $result;
	
	}
}
