<?php

namespace Proton\RigbagBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
	public function findAll() {
	
		$query = $this->createQueryBuilder('e')
							->orderBy('e.name', 'ASC')
							->getQuery();
	
		return $query->getResult();
	
	}
	
	public function findForUser( $userId ) {
	
		if( $userId ) {
			$query	= $this->createQueryBuilder('i')->getQuery();
		
			$query->join( 'i.users', 'u' );
			$query->andWhere( 'u.id=:userId' );
			$query->setParameter( 'userId', $userId );
				
			// EXECUTE
			$query->addOrderBy('i.name', 'ASC');
				
			return $query->getQuery()->getResult();
		}
		
		return array();
	}
	
	public function search( $q, $params = array() ) {
	
		extract( $params );
	
		$qb		= $this->createQueryBuilder('c');
				
		$query = $qb->where( $qb->expr()->like('c.name', ':q')  );
	
		$query->setParameter( 'q', '%' . $q . '%' );
	
				
		if( isset( $offset ) ) {
			$query->setFirstResult( $offset );
		}
		if( isset( $limit ) ) {
			$query->setMaxResults( $limit );
		}
	
		$query->addOrderBy('c.name', 'ASC');
	
	
		$result = $query->getQuery()->getResult();
	
		return $result;
	
	}
}
