<?php

namespace Proton\RigbagBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
	
	public function findForUser( $userId ) {
		
		if( $userId ) {
			
			$query = $this->createQueryBuilder('t')
							->where('t.from_user_id=:userSourceId')
							->orWhere('t.to_user_id=:userDestinationId')
							->setParameter('userSourceId', $userId )
							->setParameter( 'userDestinationId', $userId );
			
				
			$query->addOrderBy('t.created_at', 'DESC');
			
				
			$result = $query->getQuery()->getResult();
				
			return $result;
			
		}
		return array();
	}
}
